
language = [
    ('en', 'Anglais'),
    ('es', 'Espagnol'),
    ('fr-FR', 'Français'),
    ('de', 'Allemand'),
    ('it', 'Italien'),
    ('pt', 'Portugais'),
    ('nl', 'Néerlandais'),
    ('ru', 'Russe'),
    ('zh-CN', 'Chinois simplifié'),
    ('zh-TW', 'Chinois traditionnel'),
    ('ja', 'Japonais'),
    ('ko', 'Coréen'),
    ('ar', 'Arabe'),
    ('he', 'Hébreu'),
    ('tr', 'Turc'),
    ('el', 'Grec'),
    ('hi', 'Hindi'),
    ('bn', 'Bengali'),
    ('te', 'Télougou'),
    ('ta', 'Tamoul'),
    ('ur', 'Urdu'),
    ('th', 'Thaï'),
    ('id', 'Indonésien'),
    ('ms', 'Malais'),
    ('vi', 'Vietnamien'),
    ('fil', 'Philippin'),
    ('pl', 'Polonais'),
    ('sv', 'Suédois'),
    ('no', 'Norvégien'),
    ('da', 'Danois'),
    ('fi', 'Finnois'),
    ('hu', 'Hongrois'),
    ('cs', 'Tchèque'),
    ('sk', 'Slovaque'),
    ('ro', 'Roumain'),
    ('bg', 'Bulgare'),
    ('ka', 'Géorgien'),
    ('sw', 'Swahili'),
    ('tk', 'Turkmène'),
    ('kk', 'Kazakh'),
]